[book]
authors = ["cosmoplankton"]
language = "en"
multilingual = false
src = "src"
title = "Example Blog"

[output.html]
additional-css = ["theme/css/additional.css",]
additional-js = []
default-theme = "dark"
preferred-dark-theme = "ayu"
no-section-label = true
site-url = "/"
cname = ""

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 0

